name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        php: 
          - 5.6
          - 7.0
          - 7.1
          - 7.2
          - 7.3

    name: PHP ${{ matrix.php }} on ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Install PHP
      uses: nanasess/setup-php@master
      with:
        php-version: ${{ matrix.php }}
        operating-system: ${{ matrix.os }}

    - name: Install composer dependencies
      run: composer install --ignore-platform-reqs

    - name: Run tests
      run: php vendor/bin/phpunit
